### ISSUE TITLE
generar descripcion de segmentos textual (para mapas de radio y web)

### ISSUE THREAD

**Issue by hernan-alperin** [manureta/segmenter#13]
hay que poner la nueva function
indec.descripcion_segmentos
en el migrate:init
no?

**Comment by hernan-alperin** [comment]
y habría que actualizar el submodule del CORE
que está en un tag

**Comment by hernan-alperin** [comment]
se actualizo el master del CORE,
falta crear el archivo que carga la function en la DB en 
segmenter/database/migrations/

**Comment by hernan-alperin** [comment]
commit ab7d90d096cbc7b2afbe9ace4094b941543607ae (HEAD -> dividir_listado)
Author: -h <hernan.alperin@gmail.com>
Date:   Mon May 4 18:49:59 2020 -0300

    contar_vivienda decide qué registros se cuentan como vivis

**Comment by hernan-alperin** [comment]
branch descripcicion creada desde branch read-me  
(2 commits ahead of manureta/segmenter)

update submodule a rama descricpcion del CORE
CORE 055ef596c10 
http://stackoverflow.com/questions/5828324/ddg#5828396

commit f5ec5cb44320e7ecef48b01bc994ba94e105746e
Author: Hernán Alperin <alpe@alum.mit.edu>
Date:   Sat May 9 07:22:26 2020 -0300

    update submodule CORE a su branch descripcion
    para poder cargar la funcion definida en
    https://github.com/hernan-alperin/Segmentacion-CORE/tree/descripcion/descripcion_segmentos
    en el migrate
    al estilo
    database/migrations/2020_03_15_164257_instalar_funciones_segmentacion_core.php

testeando
sin push aún

**Comment by hernan-alperin** [comment]
Hernán Alperin
son 2 branchs !=
2 files?

Manuadmin
los branchs son otra cosa, no se porque los mezclas...despues tengo que decirte algo de eso...
con respescto a las funciones de migracion, a medida que se vaya modificando algo, deberia hacerse una funcion nueva que haga ese cambio.. no modificar lo que ya esta... y hay que agreaga en el down la accion de deshacer ese cambio
es mejor si vamos de a una cosa chiquita asi vamos viendo con poco y no te haces tanto enrriedo

Hernán Alperin
ok, dónde va el down?

Manuadmin
En la misma clase donde va el up
En el migrate que se agrega

Hernán Alperin
:ok_hand:
y le pongo la fecha  de prefijo al file

**Comment by hernan-alperin** [comment]
de vuelta no carga tipoviv...
lo había solucionado con un copy&paste
que me indicaste en telegram
eso está corregido en algún commit? no lo encuentro

**Comment by hernan-alperin** [comment]
necesita aceptar PR https://github.com/manureta/segmenter/pull/19

**Comment by manureta** [comment]
Ya esta todo actualizado en dev.
Como compruebo que se este generando la descripción??

**Comment by hernan-alperin** [comment]
tiene que estar creada la function
function indec.descripcion_segmentos
que genera la vista
eAAAA.descripcion_segmentos

para eso debe correr en el migrate
2020_05_10_054308_generar_descripcion_de_segmentos_textual

**Comment by manureta** [comment]
listo? cerramos?
