### ISSUE TITLE
parametrizar códigos de tipoviv que se cuentan

### ISSUE THREAD

**Issue by hernan-alperin** [manureta/segmenter#14]
https://github.com/hernan-alperin/Segmentacion-CORE/issues/7

**Comment by hernan-alperin** [comment]
JCFuchs dixit:
tengo esto... sirve? 
A Casa, Rancho
B1 Edificio o Monoblock
B2 PH o Departamento tipo casa
B3 Vivienda en Country o Barrio Cerrado
C Vivienda Colectiva con Hogares particulares: Pieza en Inquilinato, Hotel
 Familiar o Pensión
CO Vivienda Colectiva sin Hogares particulares
D Vivienda en un Lugar de Trabajo
H Vivienda en Villa
J Local no construido para habitación, con hogar particular
VE Vivienda establecimiento
FD Vivienda de uso para fin de semana
CA /CP Viviendas en Construcción

**Comment by hernan-alperin** [comment]
Silvina dixit:
se excluyen todos los CO

CO1       Campamento obrador
CO2       Colegio internado
CO3       Cuartel
CO4       Hogar de adultos mayores
CO5       Hogar de niños, niñas y adolecentes
CO6       Hogar de religiosos
CO7       Hospital
CO8       Hotel turístico, Apart Hotel, Cabañas turísticas, etc.
CO9       Prisión
CO10     Otra

**Comment by manureta** [comment]
done! #29
