### ISSUE TITLE
editar radios y radio_localidad

### ISSUE THREAD

**Issue by hernan-alperin** [manureta/segmenter#141]
en página de Radio
view que tiene en el encabezado
(luego viene el mapa, el grafo y la historia de la segmentacion)
 
localidad_1 (localidad_2 ...)
PP DDD FF RR       
tipo de radio

poner botones rojos de accciones [Acción]

1. si hay más de una localidad, 
1. 0. debajo de cada una de ellas menos la de la vista actual (color naranja) poner boton [Eliminar relación con localidad]
1. 1. si tipo es (U) urbano, poner al lado boton [Cambiar a Mixto]

2. si es una sola localidad PPDDDLLL, 
2. 0. al lado de PP DDD FF RR, poner boton [Eliminar Radio]

2. 1. si tipo es (M) mixto, al lado poner boton, [Cambiar a Urbano]
   2. si tipo es (U) urbano, al lado poner boton, [Cambiar a Mixto]
   
en referencia a 1. 0. si se acciona [Eliminar relación con localidad]
 reportar con un cartel que se realizará la siguiente acción:
 eliminar PPDDDFFRR, PPDDDLLL de la tabla radio_localidad
 ```
 delete from radio_localidad 
 where radio_id in (select id from radio where codigo = 'PPDDDFFRR')
 and localidad_id in (select id from localidad where codigo = 'PPDDDLLL');
 ```

en referencia a 1.1 si se acciona [Cambiar a Mixto]
 reportar con un cartel que se realizará la siguiente acción:
 cambiar tipo_de_radio_id en la tabla radio para el codigo PPDDDFFRR
 ```
 update radio set tipo_de_radio_id = 1 where codigo = 'PPDDDFFRR';
 ```

en referencia a 2. 0. si se acciona [Eliminar Radio]
 reportar con un cartel que se realizarán las siguientes acciones:
 1. eliminar PPDDDFFRR, PPDDDLLL de la tabla radio_localidad
 2. buscar en que esquemas se encuentra el radio PPDDDFFRR y reportar que se eliminará de todos ellos
 3. borrar el radio de la tabla radio
 
en referencia a  2.1 si se acciona [Cambiar a Urbano]
 reportar con un cartel que se realizará la siguiente acción:
 cambiar tipo_de_radio_id en la tabla radio para el codigo PPDDDFFRR
 ```
 update radio set tipo_de_radio_id = 3 where codigo = 'PPDDDFFRR';
 ```

en referencia a 2.2 si se acciona [Cambiar a Mixto]
 reportar con un cartel que se realizará la siguiente acción:
 cambiar tipo_de_radio_id en la tabla radio para el codigo PPDDDFFRR
 ```
 update radio set tipo_de_radio_id = 1 where codigo = 'PPDDDFFRR';
 ```

**Comment by hernan-alperin** [comment]
Tarea del 24/5 para @neptuso

**Comment by neptuso** [comment]
Se crearon botones de acción para:  

Caso N° 1:  si hay mas de una localidad 
 2. 0. Debajo de cada localidad excepto de la vista actual -  
 3. I.  para el caso de U (urbano) se agrega boton de acción "Cambiar a Mixto" y viceversa;
 4.  Si es 1 sola localidad:
 5.  0. Se activa botón [Eliminar Radio] (siempre y cuando haya 1 sola localidad en la vista)
 6.  i. Se aplica el caso 3.i
 6. ii Se aplica el caso 3.i

En referencia a 1.0  botón  [Eliminar Relación con localidad] : se elimina  efectivamente la relación, no se reporta más cartel informativo, además se habilita como localidad "zona rural" para poder eliminar también su relación con el radio.

En referencia a 2. 0. [Eliminar Radio] 
Se reporta cartel informativo

En referencia a 2.0 y 2.1 "Cambiar tipo de radio"(de Mixto a Urbano y viceversa):
Se ejecuta el cambio de tipo, no se reporta mas cartel.


 


 

 8.

**Comment by hernan-alperin** [comment]
está en https://gitlab.indec.gob.ar/proyecto-mandarina/mandarina/issues/498
