### ISSUE TITLE
join_ppdddcccffrrmmm.sql

### ISSUE THREAD

**Issue by hernan-alperin** [manureta/segmenter#40]
incorporar
indec.join_ppdddcccffrrmmm.sql(PPDDDCCCFFRRMMM text,
  prov integer, dpto integer, codloc integer, frac integer. radio integer, mza integer)
a la DB
ejecutar en database/migration
app/developer_docs/segmentacion-core/join_ppdddcccffrrmmm.sql

**Comment by manureta** [comment]
Hecho en database/migrations/2020_10_01_153806_fn_que_crea_tabla_ppdddcccffrrmmmll_lado_id.php
