### ISSUE TITLE
grant select to geoestadistica

### ISSUE THREAD

**Issue by hernan-alperin** [manureta/segmenter#96]
select a las tablas
radio
tipo_de_radio
corrida

access y usage de schema ePPDDDLLL
y con respecto a select de estas? 
para pgdump:
ePPDDDLL.listado 
ePPDDDLL.arc
y para analizar la segmentación?
ePPDDDLL.segmentacion

**Comment by manureta** [comment]
Do !
:)

> select a las tablas
- [ x] radio
- [ x] tipo_de_radio
- [ x] corrida
> access y usage de schema ePPDDDLLL
y con respecto a select de estas?
para pgdump:
- [ x]  ePPDDDLL.listado
- [ x]  ePPDDDLL.arc
y para analizar la segmentación?
- [ x]  ePPDDDLL.segmentacion
